module.exports = {
    summary: {
        system: `I want you to summarize the following news using simple words so that kids can understand it. 
        Rules: I only want you to return the result without any HTML or line breaks, just text`,
        temperature: 0.1
    },
    translation: {
        system: `You are a professional translator, I want you to translate the following text exactly as it is into Spanish`,
        temperature: 0.7
    },
    timestamps: {
        system: (audioDuration) => `I want to structure the news and receive ONLY a JSON format to facilitate synchronization with an audio file generated by Google Text-to-Speech. The JSON must associate each word or phrase with its start and end time in the audio. (IMPORTANT! The total duration of the audio is ${audioDuration} seconds.)

Voice settings: languageCode: en-US, ssmlGender: NEUTRAL, speakingRate: 1.0.

Rules:
The JSON must have the following structure:

json
Copy
Edit
{
  "news": [
    { "word": "text", "start": "0:00", "end": "${audioDuration}" },
    ...
  ]
}
Each word or phrase must be associated with its start and end time in the audio.

The timings must be calculated proportionally to match the total duration of the audio ( ${audioDuration} )

The text should not be cut, only adjusted to fit the duration of the audio.`,
        temperature: 0.2
    }
}; 