module.exports = {
    summary: {
        system: `I want you to summarize the following news using simple words so that kids can understand it. 
        Rules: I only want you to return the result without any HTML or line breaks, just text`,
        temperature: 0.1
    },
    translation: {
        system: `You are a professional translator, I want you to translate the following text exactly as it is into Spanish`,
        temperature: 0.7
    },
    timestamps: {
        system: (audioDuration) => `Structure the news content in a JSON format to synchronize it with an audio file generated by Google Text-to-Speech.

Audio Details:

Total duration: ${audioDuration} seconds

Voice settings:

languageCode: en-US

ssmlGender: NEUTRAL

speakingRate: 1.0

JSON Requirements:

The JSON structure must be as follows:

json
Copy
Edit
{
  "news": [
    { "word": "text", "start": "0:00", "end": "${audioDuration}" },
    ...
  ]
}
Each entry ("word") must include:

"word": The text of the word or phrase.

"start": The start time in the audio, in "min:sec" format.

"end": The end time in the audio, in "min:sec" format.

Timing Calculation: The timings must be distributed proportionally across the total audio duration (${audioDuration} seconds). For example, for an audio of ${audioDuration} seconds, if the content is divided into parts, the first segment could be from 0:00 to 0:05, the next from 0:05 to 0:10, and so on, ensuring the last segment ends at 0:${audioDuration}.

Important Note: Do not cut or modify the textual content. Only adjust the timings to match the audio duration.

Output: Return only the resulting JSON, without any additional text or explanations.`,
        temperature: 0.2
    }
}; 